- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: Add user
    ansible.builtin.user:
      name: roboshop

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp 

  - name: Extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes